# Generated by the protocol buffer compiler. DO NOT EDIT.
from dataclasses import dataclass

import betterproto

from . import sensors


@dataclass
class Frame(betterproto.Message):
    frame_timestamp_ns: int = betterproto.uint64_field(1)
    lidars: list[sensors.LidarScan] = betterproto.message_field(2)
    frame_id: int = betterproto.uint32_field(3)
