# Generated by the protocol buffer compiler. DO NOT EDIT.
from dataclasses import dataclass

import betterproto

from . import common
from . import data
from . import label


class LaserName(betterproto.Enum):
    UNKNOWN_NAME = 0
    WIM_HOR = 1
    ANPR_HOR = 2
    AMPEL_HOR = 3
    WIM_VER = 4
    ANPR_VER = 5
    AMPEL_VER = 6
    CLASS_QB2 = 7
    CLASS_OS0 = 8
    CLASS_AERIES_II = 9


@dataclass
class CameraCalibration(betterproto.Message):
    sensor_name: str = betterproto.string_field(1)
    intrinsic: list[float] = betterproto.double_field(2)


@dataclass
class CameraFrame(betterproto.Message):
    sensor_name: str = betterproto.string_field(1)
    frame_timestamp_ns: int = betterproto.uint64_field(2)
    width: int = betterproto.uint32_field(3)
    height: int = betterproto.uint32_field(4)
    encoding: str = betterproto.string_field(5)
    image_data: bytes = betterproto.bytes_field(6)
    calibration: CameraCalibration = betterproto.message_field(7)


@dataclass
class LidarScan(betterproto.Message):
    laser_name: LaserName = betterproto.enum_field(1)
    scan_timestamp_ns: int = betterproto.uint64_field(2)
    pointcloud: data.PointCloud = betterproto.message_field(3)
    calibration: common.SensorCalibration = betterproto.message_field(4)
    object_list: list[label.ObjectBBox] = betterproto.message_field(5)
